name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v3
      - uses: https://github.com/denoland/setup-deno@v1
        with:
          deno-version: v1.41.0
      - name: Test
        run: |
          make test
